apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: benchmark-nodes
  labels: 
    role: benchmark
spec:
  selector:
    matchLabels:
      role: benchmark
  template:
    metadata:
      labels:
        role: benchmark
    spec:
      nodeSelector:
        role: benchmark
      hostNetwork: true
      containers:
      - name: benchmark-container
        image: sauravchh/tasc
        imagePullPolicy: Always
        env:
        - name: BRANCH
          value: master
        - name: ROLE
          value: benchmark
        - name: AWS_ACCESS_KEY_ID
            value: ACCESS_KEY_ID_DUMMY
        - name: AWS_SECRET_ACCESS_KEY
            value: AWS_SECRET_KEY_DUMMY
