apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keynode-nodes
  labels:
    role: keynode
spec:
  selector:
    matchLabels:
      role: keynode
  template:
    metadata:
      labels:
        role: keynode
    spec:
      nodeSelector:
        role: keynode
      hostNetwork: true
      containers:
      - name: keynode-container
        image: sauravchh/tasc
        imagePullPolicy: Always
        env:
        - name: BRANCH
          value: master
        - name: ROLE
          value: keynode
        - name: MONITOR
          value: DUMMY_IP
        - name: AWS_ACCESS_KEY_ID
          value: ACCESS_KEY_ID_DUMMY
        - name: AWS_SECRET_ACCESS_KEY
          value: AWS_SECRET_KEY_DUMMY
