apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lb-nodes
  labels:
    role: lb
spec:
  selector:
    matchLabels:
      role: lb
  template:
    metadata:
      labels:
        role: lb
    spec:
      nodeSelector:
        role: lb
      hostNetwork: true
      containers:
        - name: lb-container
          image: sauravchh/tasc
          imagePullPolicy: Always
          env:
            - name: BRANCH
              value: master
            - name: ROLE
              value: lb
            - name: AWS_ACCESS_KEY_ID
              value: ACCESS_KEY_ID_DUMMY
            - name: AWS_SECRET_ACCESS_KEY
              value: AWS_SECRET_KEY_DUMMY