apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor-nodes
  labels: 
    role: monitor
spec:
  selector:
    matchLabels:
      role: monitor
  template:
    metadata:
      labels:
        role: monitor
    spec:
      nodeSelector:
        role: monitor
      hostNetwork: true
      containers:
      - name: monitor-container
        image: sauravchh/tasc
        imagePullPolicy: Always
        env:
        - name: BRANCH
          value: master
        - name: ROLE
          value: monitor
        - name: AWS_ACCESS_KEY_ID
          value: ACCESS_KEY_ID_DUMMY
        - name: AWS_SECRET_ACCESS_KEY
          value: AWS_SECRET_KEY_DUMMY