apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tasc-nodes
  labels:
    role: tasc
spec:
  selector:
    matchLabels:
      role: tasc
  template:
    metadata:
      labels:
        role: tasc
    spec:
      nodeSelector:
        role: tasc
      hostNetwork: true
      containers:
      - name: tasc-container
        image: tajshaik24/tasc
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        env:
        - name: ROLE
          value: tasc
        - name: NODE_IPS
          value: ""
        - name: KEY_ROUTER
          value: DUMMY_IP
