apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tasc-nodes
  labels:
    role: tasc
spec:
  selector:
    matchLabels:
      role: tasc
  template:
    metadata:
      labels:
        role: tasc
    spec:
      nodeSelector:
        role: tasc
      hostNetwork: true
      containers:
      - name: tasc-container
        image: sauravchh/tasc
        imagePullPolicy: Always
        env:
        - name: BRANCH
          value: master
        - name: ROLE
          value: tasc
        - name: ROUTING_ILB
          value: DUMMY_IP
        - name: MONITOR
          value: DUMMY_IP
        - name: WORKER_ILB
          value: DUMMY_IP
        - name: AWS_ACCESS_KEY_ID
          value: ACCESS_KEY_ID_DUMMY
        - name: AWS_SECRET_ACCESS_KEY
          value: AWS_SECRET_KEY_DUMMY
