apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: keynode-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: c5.2xlarge
  maxSize: FILLER
  minSize: FILLER
  role: Node
  rootVolumeSize: 32
  nodeLabels:
    role: keynode
  subnets:
    - us-east-1a

