apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: keyrouting-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: c5.2xlarge
  maxSize: 1
  minSize: 1
  rootVolumeSize: 32
  role: Node
  nodeLabels:
    role: keyrouter
  subnets:
    - us-east-1a
