apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: routing-instances
spec:
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: r4.2xlarge
  maxSize: MAX_DUMMY
  minSize: MIN_DUMMY
  role: Node
  rootVolumeSize: 32
  nodeLabels:
    role: routing
  subnets:
    - us-east-1a
